# Generated by Django 4.2.4 on 2023-08-17 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postgres', '0005_alter_product_category_alter_promotion_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postgres.promotion'),
        ),
    ]
