# Generated by Django 4.2.4 on 2023-08-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgres', '0007_product_price_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='percentage',
            field=models.IntegerField(),
        ),
    ]
